### ISSUE TITLE
4K videos are not showing in 4K on a 4K display

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-html#16]
### What is the expected behavior?
If the video is capable of 4K, it should show in 4K.

### What is the actual behavior?
The video is very obviously not in 4K when it displays on a 4K display.

### What steps can be taken to replicate the problem?
Using this Schedule: https://apps.risevision.com/schedules/details/36da4b15-027d-4443-b265-6edef8acd9f9?cid=556323b8-984c-4127-aa08-4d73d019bcb8
You can see that the 2 mins of YouTube embed is not in 4K. The same video plays using the Full Screen Video template, and is clearly in 4K

**Comment by sheadarlison** [comment]
@robb-price I did some research and I don't think YouTube lets you embed and autoplay 4K videos. There is no parameter available that will ensure that behavior. 

https://developers.google.com/youtube/iframe_api_reference 

FYI @ezequielc @mmeiers not sure if you see something different?

Thanks

**Comment by ezequielc** [comment]
Sorry, @sheadarlison, I didn't find anything specific about limiting the video quality/size in the link you shared. Could you pinpoint your findings? Thanks!

**Comment by ezequielc** [comment]
@robb-price As per our chat in Slack (https://rise-vision-inc.slack.com/archives/CCELMSZFZ/p1618930741108100), 4k plays fine when manually set or by adding `&vq=highres` to the video url. Since there is nothing wrong with the component or template, we can close this defect. Thanks!
